<?php

namespace Database\Seeders;

use App\Models\FishportVessel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FishportVesselSeeder extends Seeder
{
    /**
     * Seed the application's fishport vessel registry.
     */
    public function run(): void
    {
        $now = now();

        $vessels = [
            [
                'name' => 'MB Ziah & Noah',
                'owner_name' => 'Ziah and Noah Fisheries',
                'vessel_type' => 'Medium Commercial',
                'registration_number' => 'REG-FP-0001',
                'official_number' => 'OFF-FP-0001',
                'plate_permit_number' => 'PERMIT-0001',
                'home_port' => 'San Jose, Antique',
                'gross_tonnage' => 22.50,
                'net_tonnage' => 18.00,
                'vessel_length' => 16.20,
                'beam_width' => 4.10,
                'vessel_depth' => 2.00,
                'engine_type' => 'Diesel',
                'engine_horsepower' => 280.00,
                'hull_material' => 'Fiberglass',
                'color_markings' => 'White/Blue Stripe',
                'year_built' => 2020,
                'owner_address' => 'Brgy. San Pedro, San Jose, Antique',
                'owner_contact_number' => '09171234567',
                'owner_email' => 'owner1@fishport.local',
                'owner_government_id_number' => 'TIN-100000001',
                'business_name' => 'Ziah and Noah Fisheries',
                'captain_operator_name' => 'Captain Ramon',
                'captain_license_number' => 'LIC-0001',
                'captain_contact_number' => '09181234567',
                'captain_address' => 'San Jose, Antique',
                'registration_date' => '2026-01-10',
                'expiration_date' => '2027-01-10',
                'registration_status' => 'Active',
                'renewal_date' => '2026-12-20',
                'issued_by' => 'Fishport Management Office',
                'supporting_documents_uploaded' => true,
                'certificate_of_ownership_path' => 'seeded/certificate-0001.pdf',
                'previous_registration_path' => 'seeded/previous-0001.pdf',
                'boat_permit_license_path' => 'seeded/permit-0001.pdf',
                'engine_receipt_proof_path' => 'seeded/engine-0001.pdf',
                'valid_id_path' => 'seeded/validid-0001.pdf',
                'inspection_certificate_path' => 'seeded/inspection-0001.pdf',
                'remarks' => 'Seeded registration record.',
                'is_active' => true,
            ],
            [
                'name' => 'MB Jessa',
                'owner_name' => 'Jessa Marine Services',
                'vessel_type' => 'Small Municipal',
                'registration_number' => 'REG-FP-0002',
                'official_number' => 'OFF-FP-0002',
                'plate_permit_number' => 'PERMIT-0002',
                'home_port' => 'San Jose, Antique',
                'gross_tonnage' => 15.20,
                'net_tonnage' => 11.90,
                'vessel_length' => 12.30,
                'beam_width' => 3.10,
                'vessel_depth' => 1.70,
                'engine_type' => 'Diesel',
                'engine_horsepower' => 180.00,
                'hull_material' => 'Wood',
                'color_markings' => 'White/Red',
                'year_built' => 2019,
                'owner_address' => 'Brgy. 3, San Jose, Antique',
                'owner_contact_number' => '09171230002',
                'owner_email' => 'owner2@fishport.local',
                'owner_government_id_number' => 'TIN-100000002',
                'business_name' => 'Jessa Marine Services',
                'captain_operator_name' => 'Captain Joel',
                'captain_license_number' => 'LIC-0002',
                'captain_contact_number' => '09181230002',
                'captain_address' => 'San Jose, Antique',
                'registration_date' => '2026-01-15',
                'expiration_date' => '2027-01-15',
                'registration_status' => 'Active',
                'renewal_date' => '2026-12-25',
                'issued_by' => 'Fishport Management Office',
                'supporting_documents_uploaded' => true,
                'certificate_of_ownership_path' => 'seeded/certificate-0002.pdf',
                'previous_registration_path' => 'seeded/previous-0002.pdf',
                'boat_permit_license_path' => 'seeded/permit-0002.pdf',
                'engine_receipt_proof_path' => 'seeded/engine-0002.pdf',
                'valid_id_path' => 'seeded/validid-0002.pdf',
                'inspection_certificate_path' => 'seeded/inspection-0002.pdf',
                'remarks' => 'Seeded registration record.',
                'is_active' => true,
            ],
            [
                'name' => 'MB San Rafael',
                'owner_name' => 'San Rafael Vessel Ops',
                'vessel_type' => 'Large Commercial',
                'registration_number' => 'REG-FP-0003',
                'official_number' => 'OFF-FP-0003',
                'plate_permit_number' => 'PERMIT-0003',
                'home_port' => 'Cocoro Island',
                'gross_tonnage' => 33.80,
                'net_tonnage' => 28.10,
                'vessel_length' => 19.10,
                'beam_width' => 4.80,
                'vessel_depth' => 2.30,
                'engine_type' => 'Diesel Turbo',
                'engine_horsepower' => 420.00,
                'hull_material' => 'Steel',
                'color_markings' => 'Blue/White',
                'year_built' => 2018,
                'owner_address' => 'Cocoro Island, Antique',
                'owner_contact_number' => '09171230003',
                'owner_email' => 'owner3@fishport.local',
                'owner_government_id_number' => 'TIN-100000003',
                'business_name' => 'San Rafael Vessel Ops',
                'captain_operator_name' => 'Captain Andres',
                'captain_license_number' => 'LIC-0003',
                'captain_contact_number' => '09181230003',
                'captain_address' => 'Cocoro Island, Antique',
                'registration_date' => '2026-02-01',
                'expiration_date' => '2027-02-01',
                'registration_status' => 'Active',
                'renewal_date' => '2027-01-15',
                'issued_by' => 'Fishport Management Office',
                'supporting_documents_uploaded' => true,
                'certificate_of_ownership_path' => 'seeded/certificate-0003.pdf',
                'previous_registration_path' => 'seeded/previous-0003.pdf',
                'boat_permit_license_path' => 'seeded/permit-0003.pdf',
                'engine_receipt_proof_path' => 'seeded/engine-0003.pdf',
                'valid_id_path' => 'seeded/validid-0003.pdf',
                'inspection_certificate_path' => 'seeded/inspection-0003.pdf',
                'remarks' => 'Seeded registration record.',
                'is_active' => true,
            ],
            [
                'name' => 'MB Arlyn Mae',
                'owner_name' => 'Arlyn Mae Transport',
                'vessel_type' => 'Utility/Service',
                'registration_number' => 'REG-FP-0004',
                'official_number' => 'OFF-FP-0004',
                'plate_permit_number' => 'PERMIT-0004',
                'home_port' => 'Sulu Sea',
                'gross_tonnage' => 19.90,
                'net_tonnage' => 14.60,
                'vessel_length' => 14.10,
                'beam_width' => 3.60,
                'vessel_depth' => 1.90,
                'engine_type' => 'Diesel',
                'engine_horsepower' => 210.00,
                'hull_material' => 'Wood',
                'color_markings' => 'Green/White',
                'year_built' => 2021,
                'owner_address' => 'Brgy. 7, San Jose, Antique',
                'owner_contact_number' => '09171230004',
                'owner_email' => 'owner4@fishport.local',
                'owner_government_id_number' => 'TIN-100000004',
                'business_name' => 'Arlyn Mae Transport',
                'captain_operator_name' => 'Captain Mario',
                'captain_license_number' => 'LIC-0004',
                'captain_contact_number' => '09181230004',
                'captain_address' => 'San Jose, Antique',
                'registration_date' => '2026-02-05',
                'expiration_date' => '2027-02-05',
                'registration_status' => 'Active',
                'renewal_date' => '2027-01-20',
                'issued_by' => 'Fishport Management Office',
                'supporting_documents_uploaded' => true,
                'certificate_of_ownership_path' => 'seeded/certificate-0004.pdf',
                'previous_registration_path' => 'seeded/previous-0004.pdf',
                'boat_permit_license_path' => 'seeded/permit-0004.pdf',
                'engine_receipt_proof_path' => 'seeded/engine-0004.pdf',
                'valid_id_path' => 'seeded/validid-0004.pdf',
                'inspection_certificate_path' => 'seeded/inspection-0004.pdf',
                'remarks' => 'Seeded registration record.',
                'is_active' => true,
            ],
            [
                'name' => 'F/B Santa Maria',
                'owner_name' => 'Santa Maria Fishing Cooperative',
                'vessel_type' => 'Small Municipal',
                'registration_number' => 'REG-FP-0005',
                'official_number' => 'OFF-FP-0005',
                'plate_permit_number' => 'PERMIT-0005',
                'home_port' => 'Cuyo Island',
                'gross_tonnage' => 12.60,
                'net_tonnage' => 9.20,
                'vessel_length' => 10.80,
                'beam_width' => 2.90,
                'vessel_depth' => 1.40,
                'engine_type' => 'Gasoline',
                'engine_horsepower' => 120.00,
                'hull_material' => 'Fiberglass',
                'color_markings' => 'Yellow/White',
                'year_built' => 2022,
                'owner_address' => 'Cuyo Island, Antique',
                'owner_contact_number' => '09171230005',
                'owner_email' => 'owner5@fishport.local',
                'owner_government_id_number' => 'TIN-100000005',
                'business_name' => 'Santa Maria Fishing Cooperative',
                'captain_operator_name' => 'Captain Luis',
                'captain_license_number' => 'LIC-0005',
                'captain_contact_number' => '09181230005',
                'captain_address' => 'Cuyo Island, Antique',
                'registration_date' => '2026-02-08',
                'expiration_date' => '2027-02-08',
                'registration_status' => 'Active',
                'renewal_date' => '2027-01-25',
                'issued_by' => 'Fishport Management Office',
                'supporting_documents_uploaded' => true,
                'certificate_of_ownership_path' => 'seeded/certificate-0005.pdf',
                'previous_registration_path' => 'seeded/previous-0005.pdf',
                'boat_permit_license_path' => 'seeded/permit-0005.pdf',
                'engine_receipt_proof_path' => 'seeded/engine-0005.pdf',
                'valid_id_path' => 'seeded/validid-0005.pdf',
                'inspection_certificate_path' => 'seeded/inspection-0005.pdf',
                'remarks' => 'Seeded registration record.',
                'is_active' => true,
            ],
        ];

        foreach ($vessels as &$vessel) {
            $vessel['created_at'] = $now;
            $vessel['updated_at'] = $now;
        }
        unset($vessel);

        FishportVessel::query()->upsert(
            $vessels,
            ['name'],
            [
                'owner_name',
                'vessel_type',
                'registration_number',
                'official_number',
                'plate_permit_number',
                'home_port',
                'gross_tonnage',
                'net_tonnage',
                'vessel_length',
                'beam_width',
                'vessel_depth',
                'engine_type',
                'engine_horsepower',
                'hull_material',
                'color_markings',
                'year_built',
                'owner_address',
                'owner_contact_number',
                'owner_email',
                'owner_government_id_number',
                'business_name',
                'captain_operator_name',
                'captain_license_number',
                'captain_contact_number',
                'captain_address',
                'registration_date',
                'expiration_date',
                'registration_status',
                'renewal_date',
                'issued_by',
                'supporting_documents_uploaded',
                'certificate_of_ownership_path',
                'previous_registration_path',
                'boat_permit_license_path',
                'engine_receipt_proof_path',
                'valid_id_path',
                'inspection_certificate_path',
                'remarks',
                'is_active',
                'updated_at',
            ]
        );

        $vesselsByName = collect($vessels)->keyBy('name');
        $persistedVessels = FishportVessel::query()
            ->whereIn('name', $vesselsByName->keys()->all())
            ->get(['id', 'name']);

        foreach ($persistedVessels as $persistedVessel) {
            $seed = $vesselsByName->get($persistedVessel->name);
            if (! is_array($seed)) {
                continue;
            }

            DB::table('fishport_vessel_owners')->updateOrInsert(
                ['fishport_vessel_id' => $persistedVessel->id],
                [
                    'full_name' => $seed['owner_name'],
                    'address' => $seed['owner_address'],
                    'contact_number' => $seed['owner_contact_number'],
                    'email' => $seed['owner_email'],
                    'government_id_number' => $seed['owner_government_id_number'],
                    'business_name' => $seed['business_name'],
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );

            DB::table('fishport_vessel_operators')->updateOrInsert(
                ['fishport_vessel_id' => $persistedVessel->id],
                [
                    'name' => $seed['captain_operator_name'],
                    'license_number' => $seed['captain_license_number'],
                    'contact_number' => $seed['captain_contact_number'],
                    'address' => $seed['captain_address'],
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );

            DB::table('fishport_vessel_documents')->updateOrInsert(
                ['fishport_vessel_id' => $persistedVessel->id],
                [
                    'certificate_of_ownership_path' => $seed['certificate_of_ownership_path'],
                    'previous_registration_path' => $seed['previous_registration_path'],
                    'boat_permit_license_path' => $seed['boat_permit_license_path'],
                    'engine_receipt_proof_path' => $seed['engine_receipt_proof_path'],
                    'valid_id_path' => $seed['valid_id_path'],
                    'inspection_certificate_path' => $seed['inspection_certificate_path'],
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );

            DB::table('fishport_vessel_registrations')->updateOrInsert(
                ['fishport_vessel_id' => $persistedVessel->id],
                [
                    'registration_number' => $seed['registration_number'],
                    'official_number' => $seed['official_number'],
                    'plate_permit_number' => $seed['plate_permit_number'],
                    'home_port' => $seed['home_port'],
                    'gross_tonnage' => $seed['gross_tonnage'],
                    'net_tonnage' => $seed['net_tonnage'],
                    'vessel_length' => $seed['vessel_length'],
                    'beam_width' => $seed['beam_width'],
                    'vessel_depth' => $seed['vessel_depth'],
                    'engine_type' => $seed['engine_type'],
                    'engine_horsepower' => $seed['engine_horsepower'],
                    'hull_material' => $seed['hull_material'],
                    'color_markings' => $seed['color_markings'],
                    'year_built' => $seed['year_built'],
                    'registration_date' => $seed['registration_date'],
                    'expiration_date' => $seed['expiration_date'],
                    'registration_status' => $seed['registration_status'],
                    'renewal_date' => $seed['renewal_date'],
                    'issued_by' => $seed['issued_by'],
                    'supporting_documents_uploaded' => $seed['supporting_documents_uploaded'],
                    'remarks' => $seed['remarks'],
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );
        }
    }
}
